# Generated by Django 5.1.6 on 2026-02-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('observaciones_generales', models.TextField(blank=True, default='', verbose_name='Observaciones generales')),
                ('alergias', models.TextField(blank=True, default='', verbose_name='Alergias conocidas')),
                ('antecedentes', models.TextField(blank=True, default='', verbose_name='Antecedentes médicos')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial clínico',
                'verbose_name_plural': 'Historiales clínicos',
                'db_table': 'historial_clinico',
            },
        ),
        migrations.CreateModel(
            name='EventoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('diagnostico', 'Diagnóstico'), ('tratamiento', 'Tratamiento'), ('seguimiento', 'Seguimiento'), ('emergencia', 'Emergencia')], default='consulta', max_length=20, verbose_name='Tipo de evento')),
                ('descripcion', models.TextField(verbose_name='Descripción del evento')),
                ('sintomas', models.TextField(blank=True, default='', verbose_name='Síntomas reportados')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, default='', verbose_name='Tratamiento indicado')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del evento')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='historial.historialclinico', verbose_name='Historial clínico')),
            ],
            options={
                'verbose_name': 'Evento clínico',
                'verbose_name_plural': 'Eventos clínicos',
                'db_table': 'evento_clinico',
                'ordering': ['-fecha'],
            },
        ),
    ]
