# Generated by Django 5.1.6 on 2026-02-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas_ingresados', models.JSONField(help_text='Lista de síntomas seleccionados por el médico', verbose_name='Síntomas ingresados')),
                ('diagnostico_predicho', models.CharField(max_length=255, verbose_name='Diagnóstico predicho')),
                ('confianza', models.FloatField(help_text='Porcentaje de confianza del modelo (0-100)', verbose_name='Nivel de confianza (%)')),
                ('top_predicciones', models.JSONField(default=list, help_text='Las 3 predicciones más probables con sus porcentajes', verbose_name='Top predicciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptado', 'Aceptado por el médico'), ('rechazado', 'Rechazado por el médico')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas_medico', models.TextField(blank=True, default='', help_text='Observaciones del médico sobre la predicción', verbose_name='Notas del médico')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del diagnóstico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ia', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Resultado IA',
                'verbose_name_plural': 'Resultados IA',
                'db_table': 'resultado_ia',
                'ordering': ['-fecha'],
            },
        ),
    ]
