# Generated by Django 5.1.6 on 2026-02-17 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Médico'), ('enfermero', 'Enfermero/a')], default='medico', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('consulta', 'Consulta de datos'), ('registro', 'Registro de datos'), ('diagnostico', 'Diagnóstico IA')], max_length=20, verbose_name='Tipo de operación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'db_table': 'registro_acceso',
                'ordering': ['-fecha'],
            },
        ),
    ]
